configs: 
  phpinfo: 
    file: ./src/index.php
services: 
  phpinfo:
    command: 
      - -f 
      - src/index.php
      - -S 
      - 0.0.0.0:8080
    configs:
      - 
        mode: 0400
        source: phpinfo
        target: /src/index.php
    deploy: 
      placement: 
        constraints:
          - node.role == worker
    entrypoint: /usr/bin/php
    image: albertocuestanoriega/phpinfo:santander
    ports: 
      - 8080:8080    
version: '3.8'
